Add biclops pan-tilt head support

diff --git a/ViSP/configure b/ViSP/configure
--- a/ViSP/configure
+++ b/ViSP/configure
@@ -7395,7 +7395,7 @@ _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-char *name="foo"; int speed = 19200; char openserial(char *, int );
+const char *name="foo"; int speed = 19200; char openserial(const char *, int );
 int
 main ()
 {
@@ -7576,6 +7576,84 @@ fi
 
 
 
+#-----------------------------------------------------------------------
+# check if libBiclops, libPMD, libUtils are reachable
+echo "$as_me:$LINENO: checking whether biclops pan-tilt api works" >&5
+echo $ECHO_N "checking whether biclops pan-tilt api works... $ECHO_C" >&6
+
+  ROBOT_BICLOPS_LIBS="-lBiclops -lPMD -lUtils"
+  # save values
+  TMP_LIBS=$LIBS
+  # set linker options for a local test
+  LIBS=$ROBOT_PTUEVI_LIBS
+  # test a single function of the SBS Ptuevi bus driver
+  ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  have_robot_biclops=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+have_robot_biclops=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+  ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+  # put the saved values
+  LIBS=$TMP_LIBS
+
+  if test "x$have_robot_biclops" = "xyes"; then
+    # Biclops robot works
+    LIBS="$ROBOT_BICLOPS_LIBS $LIBS"
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_ROBOT_BICLOPS_PT 1
+_ACEOF
+
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+  else
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  fi
+
+
 
 ########################################################################
 # Add all the ViSP libraries
@@ -7607,7 +7685,7 @@ uninstall_mk=$VISP_HOME/configs/uninstall.mk
 
 depend_mk=$VISP_HOME/configs/depend.mk
 
-                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ac_config_files="$ac_config_files configs/build.mk doc/config-doxygen include/Makefile include/visp/Makefile Makefile src/Makefile src/camera/Makefile src/debug/Makefile src/exceptions/Makefile src/math/Makefile src/math/misc/Makefile src/math/transformation/Makefile src/math/matrix/Makefile src/math/robust/Makefile src/data-structure/Makefile src/robot/Makefile src/robot/robot/Makefile src/robot/simulation-robot/Makefile src/robot/real-robot/Makefile src/robot/real-robot/afma6/Makefile src/robot/real-robot/afma4/Makefile src/robot/real-robot/ptu46/Makefile src/servo/Makefile src/simulator/Makefile src/tools/Makefile src/tools/io/Makefile src/tools/geometry/Makefile src/tools/time/Makefile src/visual-feature/Makefile src/image/Makefile src/computer-vision/Makefile src/computer-vision/pose-estimation/Makefile src/computer-vision/homography-estimation/Makefile src/video-device/Makefile src/framegrabber-device/Makefile src/framegrabber-device/IC-Comp/Makefile src/framegrabber-device/1394/Makefile src/framegrabber-device/OSX-cfox/Makefile src/framegrabber-device/v4l2/Makefile src/framegrabber-device/generic-framegrabber/Makefile src/framegrabber-device/disk/Makefile src/tracking/Makefile src/tracking/dots/Makefile src/tracking/moving-edges/Makefile src/tracking/forward-projection/Makefile src/tracking/feature-builder/Makefile src/tracking/general-tracking-issues/Makefile test/Makefile test/pose/Makefile test/servo-simu/Makefile test/servo-afma4/Makefile test/servo-afma6/Makefile test/servo-ptu46/Makefile test/framegrabber/Makefile test/feature/Makefile test/math/Makefile test/image/Makefile test/tracking/Makefile test/simulator/Makefile test/homography/Makefile example/Makefile example/tracking/Makefile example/tracking/vpDot/Makefile example/image/Makefile example/simulation/Makefile example/pose-estimation/Makefile"
+                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ac_config_files="$ac_config_files configs/build.mk doc/config-doxygen include/Makefile include/visp/Makefile Makefile src/Makefile src/camera/Makefile src/debug/Makefile src/exceptions/Makefile src/math/Makefile src/math/misc/Makefile src/math/transformation/Makefile src/math/matrix/Makefile src/math/robust/Makefile src/data-structure/Makefile src/robot/Makefile src/robot/robot/Makefile src/robot/simulation-robot/Makefile src/robot/real-robot/Makefile src/robot/real-robot/afma6/Makefile src/robot/real-robot/afma4/Makefile src/robot/real-robot/ptu46/Makefile src/robot/real-robot/biclops/Makefile src/servo/Makefile src/simulator/Makefile src/tools/Makefile src/tools/io/Makefile src/tools/geometry/Makefile src/tools/time/Makefile src/visual-feature/Makefile src/image/Makefile src/computer-vision/Makefile src/computer-vision/pose-estimation/Makefile src/computer-vision/homography-estimation/Makefile src/video-device/Makefile src/framegrabber-device/Makefile src/framegrabber-device/IC-Comp/Makefile src/framegrabber-device/1394/Makefile src/framegrabber-device/OSX-cfox/Makefile src/framegrabber-device/v4l2/Makefile src/framegrabber-device/generic-framegrabber/Makefile src/framegrabber-device/disk/Makefile src/tracking/Makefile src/tracking/dots/Makefile src/tracking/moving-edges/Makefile src/tracking/forward-projection/Makefile src/tracking/feature-builder/Makefile src/tracking/general-tracking-issues/Makefile test/Makefile test/pose/Makefile test/servo-simu/Makefile test/servo-afma4/Makefile test/servo-afma6/Makefile test/servo-ptu46/Makefile test/servo-biclops/Makefile test/framegrabber/Makefile test/feature/Makefile test/math/Makefile test/image/Makefile test/tracking/Makefile test/simulator/Makefile test/homography/Makefile example/Makefile example/tracking/Makefile example/tracking/vpDot/Makefile example/image/Makefile example/simulation/Makefile example/pose-estimation/Makefile"
 
 
 ########################################################################
@@ -8174,6 +8252,7 @@ do
   "src/robot/real-robot/afma6/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/robot/real-robot/afma6/Makefile" ;;
   "src/robot/real-robot/afma4/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/robot/real-robot/afma4/Makefile" ;;
   "src/robot/real-robot/ptu46/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/robot/real-robot/ptu46/Makefile" ;;
+  "src/robot/real-robot/biclops/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/robot/real-robot/biclops/Makefile" ;;
   "src/servo/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/servo/Makefile" ;;
   "src/simulator/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/simulator/Makefile" ;;
   "src/tools/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/tools/Makefile" ;;
@@ -8205,6 +8284,7 @@ do
   "test/servo-afma4/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/servo-afma4/Makefile" ;;
   "test/servo-afma6/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/servo-afma6/Makefile" ;;
   "test/servo-ptu46/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/servo-ptu46/Makefile" ;;
+  "test/servo-biclops/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/servo-biclops/Makefile" ;;
   "test/framegrabber/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/framegrabber/Makefile" ;;
   "test/feature/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/feature/Makefile" ;;
   "test/math/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/math/Makefile" ;;
